### PR TITLE
Responsive embedded video

### PR DESCRIPTION
**Pull request by davcri**
Just discovered this wonderful project, and find out that the embedded video wasn't responsive so I made a quick fix according to [bootstrap guidelines](http://getbootstrap.com/components/#responsive-embed) :smile:

### CODE REVIEW

**Comment by athairus** [comment]
Hello, and thanks for the pull request! Just so you're aware, the entire site is due for a full revamp in the near (?) future, so this change may not be live for too long.

**Comment by athairus** [comment]
I can't believe I didn't find that when I tried to make the video responsive...

The changes are live. Thanks!

**Comment by davcri** [comment]
> Hello, and thanks for the pull request! Just so you're aware, the entire site is due for a full revamp in the  near (?) future, so this change may not be live for too long.

Nice :)  is the code hosted somewhere ? 
I'll join the IRC as soon as I can, probably the end of month I really like this project and I would like to help :smile:

**Comment by athairus** [comment]
The code for the new site is in the hands of our designer, who's writing it as we speak. He'll commit the changes to this repo once they're done.

**Pull request merged**
